import Foundation

/// Service for generating shell launcher scripts in ~/.local/bin/
struct CustomLauncherService {
    
    /// Generates bash scripts that set ANTHROPIC_BASE_URL/OPENAI_BASE_URL and
    /// pass the active model via `-m <model>` before running the target CLI tool.
    static func installLaunchers(proxyPort: Int, authToken: String = "jxproxy", model: String = "") throws {
        let localBinPath = NSString(string: "~/.local/bin").expandingTildeInPath
        let fileManager = FileManager.default
        
        if !fileManager.fileExists(atPath: localBinPath) {
            try fileManager.createDirectory(atPath: localBinPath, withIntermediateDirectories: true)
        }
        
        let modelFlag = model.isEmpty ? "" : "--model \(model) "
        let launchers: [(name: String, target: String, args: String, env: [String: String])] = [
            (
                name: "jxclaude",
                target: "claude",
                args: "\(modelFlag)--disable-slash-commands \"$@\"",
                env: [
                    "ANTHROPIC_BASE_URL": "http://127.0.0.1:\(proxyPort)",
                    "ANTHROPIC_AUTH_TOKEN": authToken,
                    "CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY": "1",
                    "CLAUDE_CODE_AUTO_COMPACT_WINDOW": "190000",
                    "DISABLE_AUTOUPDATER": "1",
                    "DISABLE_FEEDBACK_COMMAND": "1",
                    "DISABLE_ERROR_REPORTING": "1",
                ]
            ),
            (
                name: "jxcodex",
                target: "codex",
                args: "\(modelFlag)\"$@\"",
                env: [
                    "OPENAI_BASE_URL": "http://127.0.0.1:\(proxyPort)/v1",
                    "OPENAI_API_KEY": authToken,
                    "CODEX_BASE_URL": "http://127.0.0.1:\(proxyPort)/v1",
                    "CODEX_API_KEY": authToken,
                ]
            ),
            (
                name: "jxpi",
                target: "pi",
                args: "\(modelFlag)\"$@\"",
                env: [
                    "OPENAI_BASE_URL": "http://127.0.0.1:\(proxyPort)/v1",
                    "OPENAI_API_KEY": authToken,
                ]
            ),
            (
                name: "jxserver",
                target: "open",
                args: "\"$@\"",
                env: [:]
            ),
            (
                name: "llama-local",
                target: "llama-server",
                args: "\"$@\"",
                env: [
                    "LLAMA_BASE_URL": "http://127.0.0.1:8080",
                ]
            )
        ]
        
        for launcher in launchers {
            var envExports = ""
            for (key, value) in launcher.env {
                envExports += "export \(key)=\"\(value)\"\n"
            }
            
            let scriptContent: String
            if launcher.name == "jxserver" {
                scriptContent = """
                #!/bin/bash
                # Auto-generated by JXProxy
                echo "🚀 Opening JXProxy app..."
                nohup open "/Applications/JXRouter.app" > /dev/null 2>&1 &
                echo "   Use the menu bar icon to control JXProxy."
                """
            } else if launcher.name == "llama-local" {
                scriptContent = """
                #!/bin/bash
                # Auto-generated by JXProxy
                set -e
                
                MODEL_PATH="$@"
                if [ -z "$MODEL_PATH" ]; then
                    echo "❌ Usage: llama-local <path-to-model.gguf>"
                    echo "   Example: llama-local ~/models/qwythos-9b-claude-mythos-5-1m-mtp-q4_k_m.gguf"
                    exit 1
                fi
                
                if [ ! -f "$MODEL_PATH" ]; then
                    echo "❌ Model file not found: $MODEL_PATH"
                    echo "   Make sure the path to your .gguf model file is correct."
                    exit 1
                fi
                
                echo "🚀 Starting llama-server with model: $(basename "$MODEL_PATH")"
                echo "   Port: 8080"
                echo "   Context: 8192 tokens"
                echo "   Chat template: ChatML (overrides GGUF built-in)"
                echo ""
                
                # Write ChatML template to temp file (avoids shell escaping issues inline)
                # llama-server --chat-template accepts a file path with the Jinja2 template
                nohup llama-server --host 127.0.0.1 --port 8080 --model "$MODEL_PATH" --ctx-size 8192 --chat-template "$(dirname "$0")/llama-chat-template.txt" > /tmp/llama-server.log 2>&1 &
                PID=$!
                echo "📡 Server PID: $PID"
                echo ""
                
                echo "⏳ Waiting for server to be ready..."
                for i in $(seq 1 30); do
                    if curl -s http://127.0.0.1:8080/health > /dev/null 2>&1; then
                        echo "✅ Server is ready!"
                        echo ""
                        echo "   Configure JXProxy:"
                        echo "     1. Provider → llamacpp"
                        echo "     2. Model → $(basename "$MODEL_PATH" .gguf)"
                        echo "     3. Run: jxclaude"
                        echo ""
                        echo "📊 Monitor: tail -f /tmp/llama-server.log"
                        exit 0
                    fi
                    sleep 1
                done
                
                echo "❌ Server failed to start. Check: tail -f /tmp/llama-server.log"
                exit 1
                """
            } else {
                scriptContent = """
                #!/bin/bash
                # Auto-generated by JXProxy
                # Clean conflicting env vars from user profile
                unset ANTHROPIC_DEFAULT_SONNET_MODEL ANTHROPIC_DEFAULT_OPUS_MODEL ANTHROPIC_DEFAULT_HAIKU_MODEL
                \(envExports)
                echo "🚀 JXProxy: Launching \(launcher.target) on port \(proxyPort)..."
                
                REAL_PATH=$(command -v \(launcher.target) 2>/dev/null)
                if [ -z "$REAL_PATH" ]; then
                    echo "❌ Error: Could not find '\(launcher.target)' binary in PATH."
                    exit 1
                fi
                
                exec "$REAL_PATH" \(launcher.args)
                """
            }
            
            let path = "\(localBinPath)/\(launcher.name)"
            try scriptContent.write(toFile: path, atomically: true, encoding: .utf8)
            
            // Make executable
            var attributes = try fileManager.attributesOfItem(atPath: path)
            let currentPermissions = attributes[.posixPermissions] as? NSNumber ?? NSNumber(value: 0o755)
            attributes[.posixPermissions] = NSNumber(value: currentPermissions.intValue | 0o111)
            try fileManager.setAttributes(attributes, ofItemAtPath: path)
        }
        
        // Write ChatML chat template for llama-server --chat-template
        // Overrides GGUF built-in template to fix raise_exception on non-standard formats
        let chatTemplatePath = "\(localBinPath)/llama-chat-template.txt"
        let chatTemplate = """
        {%- for message in messages %}
          {%- if message.role == "system" %}
            {{- "<|im_start|>system\\n" + message.content + "<|im_end|>\\n" }}
          {%- elif message.role == "user" %}
            {{- "<|im_start|>user\\n" + message.content + "<|im_end|>\\n" }}
          {%- elif message.role == "assistant" %}
            {{- "<|im_start|>assistant\\n" + message.content + "<|im_end|>\\n" }}
          {%- endif %}
        {%- endfor %}
        """
        try chatTemplate.write(toFile: chatTemplatePath, atomically: true, encoding: .utf8)
    }
}
