import Foundation

/// Service for generating shell launcher scripts in ~/.local/bin/
struct CustomLauncherService {
    
    /// Generates bash scripts that set ANTHROPIC_BASE_URL/OPENAI_BASE_URL and
    /// pass the active model via `-m <model>` before running the target CLI tool.
    static func installLaunchers(proxyPort: Int, authToken: String = "jxproxy", model: String = "") throws {
        let localBinPath = NSString(string: "~/.local/bin").expandingTildeInPath
        let fileManager = FileManager.default
        
        if !fileManager.fileExists(atPath: localBinPath) {
            try fileManager.createDirectory(atPath: localBinPath, withIntermediateDirectories: true)
        }
        
        let modelFlag = model.isEmpty ? "" : "--model \(model) "
        let launchers: [(name: String, target: String, args: String, env: [String: String])] = [
            (
                name: "jxclaude",
                target: "claude",
                args: "\(modelFlag)--disable-slash-commands \"$@\"",
                env: [
                    "ANTHROPIC_BASE_URL": "http://127.0.0.1:\(proxyPort)",
                    "ANTHROPIC_AUTH_TOKEN": authToken,
                    "CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY": "1",
                    "CLAUDE_CODE_AUTO_COMPACT_WINDOW": "190000",
                    "DISABLE_AUTOUPDATER": "1",
                    "DISABLE_FEEDBACK_COMMAND": "1",
                    "DISABLE_ERROR_REPORTING": "1",
                ]
            ),
            (
                name: "jxcodex",
                target: "codex",
                args: "\(modelFlag)\"$@\"",
                env: [
                    "OPENAI_BASE_URL": "http://127.0.0.1:\(proxyPort)/v1",
                    "OPENAI_API_KEY": authToken,
                    "CODEX_BASE_URL": "http://127.0.0.1:\(proxyPort)/v1",
                    "CODEX_API_KEY": authToken,
                ]
            ),
            (
                name: "jxpi",
                target: "pi",
                args: "\(modelFlag)\"$@\"",
                env: [
                    "OPENAI_BASE_URL": "http://127.0.0.1:\(proxyPort)/v1",
                    "OPENAI_API_KEY": authToken,
                ]
            ),
            (
                name: "jxserver",
                target: "open",
                args: "\"$@\"",
                env: [:]
            )
        ]
        
        for launcher in launchers {
            var envExports = ""
            for (key, value) in launcher.env {
                envExports += "export \(key)=\"\(value)\"\n"
            }
            
            let scriptContent: String
            if launcher.name == "jxserver" {
                scriptContent = """
                #!/bin/bash
                # Auto-generated by JXProxy
                echo "🚀 Opening JXProxy app..."
                nohup open "/Applications/JXRouter.app" > /dev/null 2>&1 &
                echo "   Use the menu bar icon to control JXProxy."
                """
            } else {
                scriptContent = """
                #!/bin/bash
                # Auto-generated by JXProxy
                # Clean conflicting env vars from user profile
                unset ANTHROPIC_DEFAULT_SONNET_MODEL ANTHROPIC_DEFAULT_OPUS_MODEL ANTHROPIC_DEFAULT_HAIKU_MODEL
                \(envExports)
                echo "🚀 JXProxy: Launching \(launcher.target) on port \(proxyPort)..."
                
                REAL_PATH=$(command -v \(launcher.target) 2>/dev/null)
                if [ -z "$REAL_PATH" ]; then
                    echo "❌ Error: Could not find '\(launcher.target)' binary in PATH."
                    exit 1
                fi
                
                exec "$REAL_PATH" \(launcher.args)
                """
            }
            
            let path = "\(localBinPath)/\(launcher.name)"
            try scriptContent.write(toFile: path, atomically: true, encoding: .utf8)
            
            // Owner-only permissions: scripts embed auth tokens / API keys (ticket 0017)
            var attributes = try fileManager.attributesOfItem(atPath: path)
            attributes[.posixPermissions] = NSNumber(value: 0o700)
            try fileManager.setAttributes(attributes, ofItemAtPath: path)
        }

        // Re-chmod any pre-existing token-bearing launchers (ticket 0017)
        for name in ["jxclaude", "jxcodex", "jxpi", "jxserver"] {
            let existingPath = "\(localBinPath)/\(name)"
            guard fileManager.fileExists(atPath: existingPath) else { continue }
            var attrs = try fileManager.attributesOfItem(atPath: existingPath)
            attrs[.posixPermissions] = NSNumber(value: 0o700)
            try fileManager.setAttributes(attrs, ofItemAtPath: existingPath)
        }
    }
}
