import Foundation

/// Service for generating shell launcher scripts in ~/.local/bin/
struct CustomLauncherService {
    
    /// Generates bash scripts that export HTTP_PROXY before running the target CLI tool.
    static func installLaunchers(proxyPort: Int) throws {
        let localBinPath = NSString(string: "~/.local/bin").expandingTildeInPath
        let fileManager = FileManager.default
        
        if !fileManager.fileExists(atPath: localBinPath) {
            try fileManager.createDirectory(atPath: localBinPath, withIntermediateDirectories: true)
        }
        
        let launchers: [String: String] = [
            "launch_claude": "claude",
            "launch_codex": "codex"
        ]
        
        for (launcherName, targetCli) in launchers {
            let scriptContent = """
            #!/bin/bash
            # Auto-generated by JXRouter
            
            export HTTP_PROXY="http://127.0.0.1:\(proxyPort)"
            export HTTPS_PROXY="http://127.0.0.1:\(proxyPort)"
            
            echo "🚀 Launching \(targetCli) via JXRouter Proxy on port \(proxyPort)..."
            
            # Use 'command -v' to find the real binary path
            REAL_PATH=$(command -v \(targetCli) | grep -v "launch_\(targetCli)")
            
            if [ -z "$REAL_PATH" ]; then
                echo "❌ Error: Could not find original '\(targetCli)' binary in PATH."
                exit 1
            fi
            
            exec "$REAL_PATH" "$@"
            """
            
            let path = "\(localBinPath)/\(launcherName)"
            try scriptContent.write(toFile: path, atomically: true, encoding: .utf8)
            
            // Make executable
            var attributes = try fileManager.attributesOfItem(atPath: path)
            let currentPermissions = attributes[.posixPermissions] as? NSNumber ?? NSNumber(value: 0o755)
            attributes[.posixPermissions] = NSNumber(value: currentPermissions.intValue | 0o111)
            try fileManager.setAttributes(attributes, ofItemAtPath: path)
        }
    }
}
